### ISSUE TITLE
Test case failed 

### ISSUE THREAD

**Issue by Biruntha** [wso2-extensions/esb-connector-amazons3#23]
**Description:**
Results :

Failed tests:   testCreateBucketForBucketReplication(org.wso2.carbon.connector.integration.test.amazons3.AmazonS3ConnectorIntegrationTest): expected:<200> but was:<400>
testCreateBucketLifecycleWithMandatoryParameters(org.wso2.carbon.connector.integration.test.amazons3.AmazonS3ConnectorIntegrationTest): expected:<200> but was:<400>
testCreateObjectCopyMandatoryParameters(org.wso2.carbon.connector.integration.test.amazons3.AmazonS3ConnectorIntegrationTest): expected:<200> but was:<404>
testDeleteMultipleObjectsWithMandatoryParameters(org.wso2.carbon.connector.integration.test.amazons3.AmazonS3ConnectorIntegrationTest): expected:<200> but was:<404>
testCreateBucketACLWithMandatoryParameters(org.wso2.carbon.connector.integration.test.amazons3.AmazonS3ConnectorIntegrationTest): expected:<200> but was:<400>
testDeleteBucketWebsiteWithMandatoryParameters(org.wso2.carbon.connector.integration.test.amazons3.AmazonS3ConnectorIntegrationTest): expected:<204> but was:<400>
testSetBucketACLWithMandatoryParameters(org.wso2.carbon.connector.integration.test.amazons3.AmazonS3ConnectorIntegrationTest): expected:<200> but was:<400>
testUploadPartCopyWithMandatoryParameters(org.wso2.carbon.connector.integration.test.amazons3.AmazonS3ConnectorIntegrationTest): String index out of range: -6
testCreateObjectACLWithNegativeCase(org.wso2.carbon.connector.integration.test.amazons3.AmazonS3ConnectorIntegrationTest): expected:<404> but was:<400>

Tests run: 99, Failures: 9, Errors: 0, Skipped: 20

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by keerthu** [comment]
Fixed in https://github.com/wso2-extensions/esb-connector-amazons3/pull/25
