### ISSUE TITLE
Unable to get getObjects response

### ISSUE THREAD

**Issue by Sumathi243** [wso2-extensions/esb-connector-amazons3#36]
**Description:**
Unable to get getObjects response

**Suggested Labels:**
wso2,ei,connectors,aws s3 connector, getObject

**Affected Product Version:**
Amazon S3 Connector 1.0.9

**OS, DB, other environment details and versions:**    
Windows 10 64-bit

**Steps to reproduce:**
I have simply tried getObjects method from the link `https://github.com/wso2-extensions/esb-connector-amazons3/blob/master/docs/objects.md#getting-an-object` 
but i didnt get proper response, null response only coming. Kindly do the needful.

**Related Issues:**

**Comment by abeykoon** [comment]
Please refer to example : https://ei.docs.wso2.com/en/latest/micro-integrator/references/connectors/amazons3-connector/amazons3-connector-example/
