### ISSUE TITLE
Reading XML files from S3 having an XML Prolog cause exception downstream

### ISSUE THREAD

**Issue by thijsvolders** [wso2-extensions/esb-connector-amazons3#59]
**Description:**
When reading an XML file using the getObject function then the message-transformation results in an error when that XML-file contains an XML-prolog at its start.

`Caused by: com.ctc.wstx.exc.WstxParsingException: Illegal processing instruction target ("xml"); xml (case insensitive) is reserved by the specs.`

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
v2.0.3

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
Attempt to read an XML file from an S3 location having an XML-prolog at the beginning (i.e. having <?xml version="1.0" encoding="utf-8"?>).

**Comment by thijsvolders** [comment]
I removed the PR as I noticed the proposed solution wasn't optimally solved. The issue still persists though in the mentioned version of the S3 connector

**Comment by anupama-pathirage** [comment]
Moved the issue to https://github.com/wso2/micro-integrator/issues/3466
