### ISSUE TITLE
ERROR {InvokeMediator} - {api:S3ConnectorTestAPI} Sequence template org.wso2.carbon.connector.amazons3.createBucket cannot be found

### ISSUE THREAD

**Issue by logeshkumarradhakrishnan** [wso2-extensions/esb-connector-amazons3#65]
**Description:**

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by anupama-pathirage** [comment]
Moved the issue to https://github.com/wso2/micro-integrator/issues/3456 hence closing.
